### ISSUE TITLE
Hi, is there a paper published with the repository?

### ISSUE THREAD

**Issue by mrayur** [taliaborofsky/SocialLearning_Payoff#1]
Hi, the payoff learning is a very interesting topic but lacking exploration, is there a published paper with your shared repository?

**Comment by taliaborofsky** [comment]
Hi, thank you for your interest. Yes there is:

Borofsky, T., & Feldman, M. W. (2022). Success-biased social learning in a
one-consumer, two-resource model. *Theoretical Population Biology*, *146*,
29-35.

**Comment by mrayur** [comment]
Thanks for your reply!
